### PR TITLE
Bump to CP 5.0, improve life for Windows users by making commands self-contained in Docker

### PR DESCRIPTION
**Pull request by rmoff**

### CODE REVIEW

**Comment by rmoff** [comment]
@tlberglund plz review / merge. Thanks.

**Comment by tlberglund** [comment]
In the 4.1 version, I've gotten good results bumping people to 4GB. Is 8GB necessary cuz of the 5.0 upgrade?

**Comment by tlberglund** [comment]
Also, this is about a billion times more user-friendly and prettier now. Thank you.

**Comment by rmoff** [comment]
8GB is what we use in lots of the other tutorials and quickstarts - I've
not tested with 4GB, but I've never had any problems with 8GB either :)

**Comment by tlberglund** [comment]
Kewl. I'll test with 4GB and reduce it in the text if it works. The proof will be if we can get a room full of people to do it with four. :)

**Pull request merged**
